# URL: http://www.practicepython.org/
# Author: Rohit Gupta
# Date Scheduled: September 01, 2017
# Date Written: November 29, 2018
# Version 1.0
# Problem Exercise: 18
import datetime
import random


def user_loop():
    print("Do you want to run this again?")
    loop_status = input("Please press yes to continue and no to exit: ")
    if loop_status == 'no':
        print("Goodbye, {}".format(user_name))
    else:
        main()


def main():
    computer_num = random.sample(range(1, 9), 4)
    print("The random number generated by computer is {}".format(computer_num))
    print("""For every digit that the you guessed correctly in the correct place, you have a cow. 
    For every digit that you guessed correctly in the wrong place is a bull. 
    Every time you makes a guess, you will know how many cows and bulls you have. 
    Once the guess is a correct number, the game is over. 
    We will keep track of the number of guesses you make throughout the game and tell you at the end""")
    print("Game ends when you have 4 bulls")
    user_num = input("Please guess the 4 digit number generated by your computer: ")
    print(type(user_num))
    user_list = list(map(int, str(user_num)))
    print(user_list)
    print(computer_num)
    cows = 0
    bulls = 0
    count = 0
    while computer_num != user_list:
        if user_list == computer_num:
            count += 1
            print("Congratulations, you have won in {} try, computer guessed {}".format(count, computer_num))
            user_loop()
        elif len(user_num) != len(computer_num):
            print("Error!!! Please enter a 4 digit number only")
            user_loop()

        else:
            count += 1
            for i in range(0, len(user_list)):
                if user_list[i] == computer_num[i]:
                    cows += 1

            for i in range(0, len(user_list)):
                if user_list[i] in computer_num:
                    bulls += 1


if __name__ == '__main__':
    print("Welcome to the Program to play the game Cow and Bull")
    user_name = input('Please enter your name: ')
    run_time = datetime.datetime.now()
    print('Welcome {}, your interaction with the program started at {}'.format(user_name, run_time))
    main()

